[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "swi-prolog", "clisp"]

[phases.install]
cmds = ["python3 -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = ". /opt/venv/bin/activate && python prueba.py"
